services:
  main:
    container_name: granat-nauki_main
    build:
      context: .
      dockerfile: main/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./main:/repo/main
      - ./packages:/repo/packages
      - /repo/node_modules
      - /repo/main/node_modules
      - /repo/packages/contracts/node_modules
      - /repo/main/.next
    env_file:
      - ./main/.env

  admin:
    container_name: granat-nauki_admin
    build:
      context: .
      dockerfile: admin/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./admin:/repo/admin
      - ./packages:/repo/packages
      - /repo/node_modules
      - /repo/admin/node_modules
      - /repo/packages/contracts/node_modules
    environment:
      - API_PROXY_TARGET=http://main:3000

  db:
    container_name: granat-nauki_db
    image: postgres:18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - app-network

# логи
  dozzle:
    image: amir20/dozzle:latest
    container_name: granat-nauki_dozzle
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge