services:
  backend:
    container_name: granat-nauki_backend
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    container_name: granat-nauki_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  admin:
    container_name: granat-nauki_admin
    build: ./admin
    ports:
      - "3001:3001"
    volumes:
      - ./admin:/app
      - /app/node_modules
    env_file:
      - ./admin/.env
    depends_on:
      - backend
    networks:
      - app-network

  db:
    container_name: granat-nauki_db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge